version: '3'
services:
  app:
    build: .
    container_name: app
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
